baseURL: "https://isabellajasmine.com/"
languageCode: "en-us"
title: "Isabella Jasmine"

theme: "hugo-theme-gallery"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "Painting"
      url: "/painting/"
      weight: 3
    - name: "Sculpture"
      url: "/sculpture/"
      weight: 2
    - name: "Architectural & Landscape"
      url: "/architectural_and_landscape/"
      weight: 1
    - name: "Other"
      url: "/other/"
      weight: 4
    - name: "About Me"
      url: "/about/"
      weight: 5
    - name: "Contact"
      url: "/contact/"
      weight: 6

params:
  description: "Bella's Portfolio"
